name: Utils CI

on:
  pull_request:
    branches:
      - main

jobs:
  utils-test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Depedencies
        run: |
          npm config set legacy-peer-deps true
          npm ci
      - name: Build
        run: npm run build
      - name: Test Utils
        run: npm test
